### ISSUE TITLE
Sphinx 4 Support

### ISSUE THREAD

**Issue by Daltz333** [executablebooks/meta#306]
Sphinx 4 is scheduled to be released this month. It (sphinx-panels) is currently marked as incompatible.

**Comment by chrisjsewell** [comment]
Release plan issue here: https://github.com/sphinx-doc/sphinx/issues/9056

**Comment by chrisjsewell** [comment]
Note when I upgrade things to sphinx 4, I will consider dropping support for sphinx 2. I think that's reasonable, to support the latest 2 version of sphinx (3.0.0 was released Apr 06, 2020)
cc @choldgraf @mmcky

**Comment by chrisjsewell** [comment]
For reference:

```markdown
Release 4.0.0 beta1 (released Apr 12, 2021)
===========================================

Dependencies
------------

* Drop python 3.5 support
* Drop docutils 0.12 and 0.13 support
* LaTeX: add ``tex-gyre`` font dependency

Incompatible changes
--------------------

* #8539: autodoc: info-field-list is generated into the class description when
  ``autodoc_typehints='description'`` and ``autoclass_content='class'`` set
* #8898: extlinks: "%s" becomes required keyword in the link caption string
* domain: The ``Index`` class becomes subclasses of ``abc.ABC`` to indicate
  methods that must be overrided in the concrete classes
* #4826: py domain: The structure of python objects is changed.  A boolean value
  is added to indicate that the python object is canonical one
* #7425: MathJax: The MathJax was changed from 2 to 3. Users using a custom
  MathJax configuration may have to set the old MathJax path or update their
  configuration for version 3. See :mod:`sphinx.ext.mathjax`.
* #7784: i18n: The msgid for alt text of image is changed
* #5560: napoleon: :confval:`napoleon_use_param` also affect "other parameters"
  section
* #7996: manpage: Make a section directory on build manpage by default (see
  :confval:`man_make_section_directory`)
* #7849: html: Change the default setting of
  :confval:`html_codeblock_linenos_style` to ``'inline'``
* #8380: html search: search results are wrapped with ``<p>`` instead of
  ``<div>``
* html theme: Move a script tag for documentation_options.js in
  basic/layout.html to ``script_files`` variable
* html theme: Move CSS tags in basic/layout.html to ``css_files`` variable
* #8915: html theme: Emit a warning for sphinx_rtd_theme-0.2.4 or older
* #8508: LaTeX: uplatex becomes a default setting of latex_engine for Japanese
  documents
* #5977: py domain: ``:var:``, ``:cvar:`` and ``:ivar:`` fields do not create
  cross-references
* #4550: The ``align`` attribute of ``figure`` and ``table`` nodes becomes
  ``None`` by default instead of ``'default'``
* #8769: LaTeX refactoring: split sphinx.sty into multiple files and rename
  some auxiliary files created in ``latex`` build output repertory
* #8937: Use explicit title instead of <no title>
* #8487: The :file: option for csv-table directive now recognizes an absolute
  path as a relative path from source directory

Deprecated
----------

* :confval:`html_codeblock_linenos_style`
* ``favicon`` and ``logo`` variable in HTML templates
* ``sphinx.directives.patches.CSVTable``
* ``sphinx.directives.patches.ListTable``
* ``sphinx.directives.patches.RSTTable``
* ``sphinx.ext.autodoc.directive.DocumenterBridge.filename_set``
* ``sphinx.ext.autodoc.directive.DocumenterBridge.warn()``
* ``sphinx.registry.SphinxComponentRegistry.get_source_input()``
* ``sphinx.registry.SphinxComponentRegistry.source_inputs``
* ``sphinx.transforms.FigureAligner``
* ``sphinx.util.pycompat.convert_with_2to3()``
* ``sphinx.util.pycompat.execfile_()``
* ``sphinx.util.smartypants``
* ``sphinx.util.typing.DirectiveOption``

Features added
--------------

* #8924: autodoc: Support ``bound`` argument for TypeVar
* #7383: autodoc: Support typehints for properties
* #5603: autodoc: Allow to refer to a python class using its canonical name
  when the class has two different names; a canonical name and an alias name
* #8539: autodoc: Add :confval:`autodoc_typehints_description_target` to control
  the behavior of ``autodoc_typehints=description``
* #8841: autodoc: :confval:`autodoc_docstring_signature` will continue to look
  for multiple signature lines without backslash character
* #7549: autosummary: Enable :confval:`autosummary_generate` by default
* #8898: extlinks: Allow %s in link caption string
* #4826: py domain: Add ``:canonical:`` option to python directives to describe
  the location where the object is defined
* #7199: py domain: Add :confval:`python_use_unqualified_type_names` to suppress
  the module name of the python reference if it can be resolved (experimental)
* #7068: py domain: Add :rst:dir:`py:property` directive to describe a property
* #7784: i18n: The alt text for image is translated by default (without
  :confval:`gettext_additional_targets` setting)
* #2018: html: :confval:`html_favicon` and :confval:`html_logo` now accept URL
  for the image
* #8070: html search: Support searching for 2characters word
* #9036: html theme: Allow to inherite the search page
* #8938: imgconverter: Show the error of the command availability check
* #7830: Add debug logs for change detection of sources and templates
* #8201: Emit a warning if toctree contains duplicated entries
* #8326: ``master_doc`` is now renamed to :confval:`root_doc`
* #8942: C++, add support for the C++20 spaceship operator, ``<=>``.
* #7199: A new node, ``sphinx.addnodes.pending_xref_condition`` has been added.
  It can be used to choose appropriate content of the reference by conditions.

Bugs fixed
----------

* #8917: autodoc: Raises a warning if function has wrong __globals__ value
* #8415: autodoc: a TypeVar imported from other module is not resolved (in
  Python 3.7 or above)
* #8992: autodoc: Failed to resolve types.TracebackType type annotation
* #8905: html: html_add_permalinks=None and html_add_permalinks="" are ignored
* #8380: html search: Paragraphs in search results are not identified as ``<p>``
* #8915: html theme: The translation of sphinx_rtd_theme does not work
* #8342: Emit a warning if a unknown domain is given for directive or role (ex.
  ``:unknown:doc:``)
* #7241: LaTeX: No wrapping for ``cpp:enumerator``
* #8711: LaTeX: backticks in code-blocks trigger latexpdf build warning (and font
  change) with late TeXLive 2019
* #8253: LaTeX: Figures with no size defined get overscaled (compared to images
  with size explicitly set in pixels) (fixed for ``'pdflatex'/'lualatex'`` only)
* #8881: LaTeX: The depth of bookmarks panel in PDF is not enough for navigation
* #8874: LaTeX: the fix to two minor Pygments LaTeXFormatter output issues ignore
  Pygments style
* #8925: LaTeX: 3.5.0 ``verbatimmaxunderfull`` setting does not work as
  expected
* #8980: LaTeX: missing line break in ``\pysigline``
* #8995: LaTeX: legacy ``\pysiglinewithargsret`` does not compute correctly
  available  horizontal space and should use a ragged right style
* #9009: LaTeX: "release" value with underscore leads to invalid LaTeX
* #8911: C++: remove the longest matching prefix in
  :confval:`cpp_index_common_prefix` instead of the first that matches.
* C, properly reject function declarations when a keyword is used
  as parameter name.
* #8933: viewcode: Failed to create back-links on parallel build
* #8960: C and C++, fix rendering of (member) function pointer types in
  function parameter lists.
* C++, fix linking of names in array declarators, pointer to member
  (function) declarators, and in the argument to ``sizeof...``.
* C, fix linking of names in array declarators.
```

**Comment by chrisjsewell** [comment]
One thing that will definitely need changing in myst-parser:

*  sphinx-doc/sphinx#8195: mathjax: Rename :confval:`mathjax_config` to
  :confval:`mathjax2_config` and add :confval:`mathjax3_config`

**Comment by choldgraf** [comment]
If we are only going to support the last two versions of sphinx we should document this as an EBP practice. Cc  the @executablebooks/ebpteam to see if anyone has a big objection

I am fine with it - it's going to be a big burden if we must support many major versions

**Comment by Daltz333** [comment]
Sphinx 2 is actually the main version of Sphinx for a huge number of packages. So I'm supportive of the past two. So 4-3-2, no 1. Then 5,4,3

**Comment by chrisjsewell** [comment]
But this would not preclude people using older versions of the EBP packages, if people do want to still use sphinx 2.
These projects though have had over a year now to update to sphinx 3, so I am skeptical if they ever will 😬 Perhaps it would be helpful if you could list some of the packages that you feel are important but do not yet support sphinx 3?

**Comment by choldgraf** [comment]
Here's the last 120 days of [PyPI installs for Sphinx](https://pypistats.org/packages/sphinx):

![image](https://user-images.githubusercontent.com/1839645/116278206-23c5b280-a73b-11eb-9ad3-bc1db3f34121.png)

Looks like Sphinx 2 is at about 7%. I'd expect that to lower further once Sphinx 4 comes out, but it's a bit hard to say because there was a *long* time between Sphinx 2 and 3, and relatively much less time before Sphinx 4.

**Comment by hukkinj1** [comment]
@choldgraf I think you misinterpret the data. The number "2" stands for Python2, not Sphinx2.

Sphinx2 can be installed on Python3 in which case it will show in the 85%.

**Comment by choldgraf** [comment]
Ahh yes you're right @hukkinj1 , I always misinterpret those plots. Will remove it to reduce noise.

**Comment by choldgraf** [comment]
OK better link - here's a plot of actual Sphinx version installs (I think 😅)

https://pepy.tech/project/sphinx?versions=3.5.4&versions=4.0.0b1&versions=2.4.4&versions=2.3.1&versions=1.8.5

![image](https://user-images.githubusercontent.com/1839645/116440801-aadf5d00-a805-11eb-9cec-b315d0fc2089.png)

Funnily enough, it's about 80% Sphinx 3 and Sphinx 1 has more installs than Sphinx 2 (my guess is legacy enterprise deployments and such).

So I think that this is still a decent suggestion that it's OK to deprecate Sphinx 2 support, IMO.

**Comment by astrojuanlu** [comment]
I confirm that trying to use MyST-Parser with Sphinx 4 gives a warning related to the MathJax configuration:

```
Traceback (most recent call last):
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/application.py", line 350, in build
    self.builder.build_update()
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 292, in build_update
    self.build(to_build,
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 356, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 530, in write
    self._write_serial(sorted(docnames))
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 540, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/util/logging.py", line 213, in pending_warnings
    memhandler.flushTo(logger)
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/util/logging.py", line 178, in flushTo
    logger.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 946, in handle
    rv = self.filter(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 807, in filter
    result = f.filter(record)
  File "/home/juanlu/Projects/LSF/poliastro/library/.tox/docs/lib/python3.8/site-packages/sphinx/util/logging.py", line 423, in filter
    raise exc
sphinx.errors.SphinxWarning: mathjax_config/mathjax2_config does not work for the current MathJax version, use mathjax3_config instead

Warning, treated as error:
mathjax_config/mathjax2_config does not work for the current MathJax version, use mathjax3_config instead
```

I tried the first silly thing that came to mind, without success:

```patch
diff --git a/docs/source/conf.py b/docs/source/conf.py
index ffa8bf62..25a3b0e4 100644
--- a/docs/source/conf.py
+++ b/docs/source/conf.py
@@ -363,3 +363,10 @@ exclude_patterns.append('_autoapi_templates/python/module.rst')
 suppress_warnings.append('ref.python')
 
 myst_update_mathjax = False
+mathjax3_config = {}
+mathjax3_config["tex2jax"] = {
+      "inlineMath": [["\\(", "\\)"]],
+      "displayMath": [["\\[", "\\]"]],
+      "processRefs": False,
+      "processEnvironments": False,
+}
```

**Comment by astrojuanlu** [comment]
Sorry, I think this is just a Sphinx thing. The patch that works involves updating the MathJax path so it uses version 2:

```patch
diff --git a/docs/source/conf.py b/docs/source/conf.py
index ffa8bf62..cf8a7164 100644
--- a/docs/source/conf.py
+++ b/docs/source/conf.py
@@ -363,3 +363,4 @@ exclude_patterns.append('_autoapi_templates/python/module.rst')
 suppress_warnings.append('ref.python')
 
 myst_update_mathjax = False
+mathjax_path = "https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
```

**Comment by astrojuanlu** [comment]
_Well, actually_ it was a bad interaction between nbsphinx and Sphinx 4, a new nbsphinx release solved it https://github.com/sphinx-doc/sphinx/issues/9148#issuecomment-829380292. Sorry for the noise, will hide these comments as off-topic.

**Comment by jpmckinney** [comment]
1.8.5 is probably so high because for a long time it was the default version installed by ReadTheDocs.
